LastBIOSFolder = ""
UITheme = ""
RecentROM = []
FastForwardFPS = 1000.0
AudioSync = false
PauseLostFocus = false
TargetFPS = 60.0
LimitFPS = true
SlowmoFPS = 30.0

[DLDI]
FolderPath = ""
FolderSync = false
ReadOnly = false
ImagePath = "dldi.bin"
ImageSize = 0
Enable = false

[DS]
FirmwarePath = ""
BIOS7Path = ""
BIOS9Path = ""

[Mouse]
Hide = false
HideSeconds = 5

[DSi]
FullBIOSBoot = false
FirmwarePath = ""
BIOS9Path = ""
BIOS7Path = ""
NANDPath = ""

[DSi.DSP]
HLE = true

[DSi.SD]
FolderPath = ""
FolderSync = false
ReadOnly = false
ImagePath = "dsisd.bin"
ImageSize = 0
Enable = false

[DSi.Camera1]
DeviceName = ""
ImagePath = ""
InputType = 0
XFlip = false

[DSi.Camera0]
DeviceName = ""
ImagePath = ""
InputType = 0
XFlip = false

[3D]
Renderer = 0

[MP]
AudioMode = 1
RecvTimeout = 25

[Savestate]
RelocSRAM = false

[LAN]
DirectMode = false

[Instance0]
JoystickID = 0
EnableCheats = false

[Instance0.Gdb]
Enabled = false

[Instance0.Gdb.ARM9]
BreakOnStartup = false
Port = 3333

[Instance0.Gdb.ARM7]
BreakOnStartup = false
Port = 3334

[Instance0.Window1]
Enabled = false

[Instance0.Window3]
Enabled = false

[Instance0.Joystick]
HK_GuitarGripBlue = -1
HK_GuitarGripYellow = -1
HK_GuitarGripGreen = -1
HK_SlowMoToggle = -1
HK_Lid = -1
Y = 2
HK_FrameStep = -1
HK_SolarSensorIncrease = -1
HK_GuitarGripRed = -1
L = 35782655
R = 86114303
Up = 17891585
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = 65794
Start = 7
Select = 6
X = 3
B = 0
Down = 16843012
A = 1
HK_Mic = -1
HK_FastForward = -1
HK_FrameLimitToggle = -1
Left = 1114376
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
HK_Reset = -1
HK_PowerButton = -1
HK_VolumeDown = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_FastForwardToggle = -1

[Instance0.Window2]
Enabled = false

[Instance0.Keyboard]
HK_GuitarGripBlue = -1
HK_GuitarGripYellow = -1
HK_GuitarGripGreen = -1
HK_SlowMoToggle = -1
HK_Lid = -1
Y = -1
HK_FrameStep = -1
HK_SolarSensorIncrease = -1
HK_GuitarGripRed = -1
L = -1
R = -1
Up = -1
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = -1
Start = -1
Select = -1
X = -1
B = -1
Down = -1
A = -1
HK_Mic = -1
HK_FastForward = -1
HK_FrameLimitToggle = -1
Left = -1
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
HK_Reset = -1
HK_PowerButton = -1
HK_VolumeDown = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_FastForwardToggle = -1

[Instance0.Audio]
DSiVolumeSync = false
Volume = 256

[Instance0.Firmware]
Username = "melonDS"

[Instance0.Window0]
Enabled = true
ScreenFilter = false
ScreenAspectTop = 0
IntegerScaling = false
ScreenSizing = 0
ScreenSwap = false
ScreenGap = 0
ScreenAspectBot = 0
ScreenRotation = 0
ScreenLayout = 0
Geometry = "AdnQywADAAAAAAAAAAAAAAAACf8AAAT/AAAAAAAAAAAAAAD/AAABlQAAAAACAAAACgAAAAAAAAAAFwAACf8AAAT/"
ShowOSD = true

[Emu]
DirectBoot = true
ExternalBIOSEnable = false
ConsoleType = 0

[JIT]
MaxBlockSize = 32
FastMemory = true
LiteralOptimisations = true
BranchOptimisations = true
Enable = false

[Screen]
UseGL = false

[Mic]
WavPath = ""
Device = ""
InputType = 1
